[package]
name = "deno_core_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.160"
tokio = { version = "1.0", features = ["full"] }
serde_v8 = "0.71"